episodes = 10000
horizon = 1000
environment = 'HumanoidBulletEnv'
agent_type = 'LSPHierarchicalRL'
replay_buffer_capacity = 10e4
random_sample_num = 1000
agent_update_batch_size = 256
checkpoint_interval = 10
checkpoint = ''
test_interval = 50
test_times = 5
policy_switch_samples = [1e5]



[agent]
subpolicy_coupling_layer_num = 2
gamma = 0.99
target_smoothing_rate = 0.01
alpha = 0.2
target_update_interval = 1
critic_hidden_layer_num = 128
critic_hidden_layer_size = 2
learning_rate = 3.0e-4